-- Généré par scripts/generer_referentiels.mjs à partir de 00_REFERENTIELS. À lancer après la migration 8.
-- Relancer ce script est sans danger : les lignes existantes sont mises à jour, rien n'est supprimé.

-- Agences (pont bascule). Les 4 sites marqués « nouveau » n'étaient pas dans le seed MAD.
insert into agences(code, nom, pont_bascule) values
  ('BAF', 'Bafoussam', 'Disponible'),
  ('BGT', 'Bangangté', 'Agence sans pont'),
  ('BGU', 'Bangou', 'Agence sans pont'),
  ('BER', 'Bertoua', 'Disponible'),
  ('BUE', 'Buea', 'Agence sans pont'),
  ('DLA', 'Douala', 'Disponible'),
  ('EBO', 'Ebolowa', 'Disponible'),
  ('EDE', 'Edéa', 'Disponible'),
  ('GAR', 'Garoua', 'Disponible'),
  ('KRI', 'Kribi', 'Disponible'),
  ('KUM', 'Kumba', 'Agence sans pont'),
  ('LIM', 'Limbé', 'Disponible'),
  ('MAR', 'Maroua', 'Disponible'),
  ('MEY', 'Meyomessala', 'Agence sans pont'),
  ('NGA', 'Ngaoundéré', 'Disponible'),
  ('SAN', 'Sangmélima', 'Disponible'),
  ('YAO', 'Yaoundé', 'Disponible')
on conflict (code) do update set pont_bascule = excluded.pont_bascule;

-- Parc : camions et engins. L'état est « Disponible » par défaut ; il passe à « Immobilisé » à l'import des besoins.
insert into parc(code, agence_code, famille, type_vehicule, remarque) values
  ('921247', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('AM053', 'BAF', 'Camion', 'AMPLIROLL', null),
  ('AM067', 'BAF', 'Camion', 'AMPLIROLL', null),
  ('BO075', 'BAF', 'Camion', 'BOM', null),
  ('BO076', 'BAF', 'Camion', 'BOM', null),
  ('BO081', 'BAF', 'Camion', 'BOM', null),
  ('BO096', 'BAF', 'Camion', 'BOM', null),
  ('BO165', 'BAF', 'Camion', 'BOM', null),
  ('BU02-006', 'BAF', 'Engin', 'BULDOZER', null),
  ('BX032', 'BAF', 'Camion', 'BOM X', null),
  ('CE 212 FR', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE 432 NR', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE 622 KM', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE 981 PA', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT 364 IH', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « LT364 IH » (BANGANGTE)'),
  ('LT083KX', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « LT083 KX » (BANGANGTE)'),
  ('MB012', 'BAF', 'Camion', 'MINI BOM', null),
  ('MG002', 'BAF', 'Camion', 'MOOVIE GRUE', 'Doublon possible : « MG 002 » (KRIBI)'),
  ('NO 470 AT', 'BAF', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VP036', 'BAF', 'Camion', 'VILLE DE PARIS', null),
  ('VP042', 'BAF', 'Camion', 'VILLE DE PARIS', null),
  ('VP087', 'BAF', 'Camion', 'VILLE DE PARIS', null),
  ('921217', 'BGT', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO098', 'BGT', 'Camion', 'BOM', null),
  ('LT083 KX', 'BGT', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « LT083KX » (BAFOUSSAM)'),
  ('LT364 IH', 'BGT', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « LT 364 IH » (BAFOUSSAM)'),
  ('LT772 AZ', 'BGT', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO098B', 'BGU', 'Camion', 'BOM', null),
  ('094310', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('320C', 'BER', 'Engin', 'EXCAVATRICE', null),
  ('471163', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('471164', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('655D', 'BER', 'Engin', 'PELLE CHARGEUSE', null),
  ('AM027', 'BER', 'Camion', 'AMPLIROLL', null),
  ('AM070', 'BER', 'Camion', 'AMPLIROLL', null),
  ('BO093', 'BER', 'Camion', 'BOM', null),
  ('BO168', 'BER', 'Camion', 'BOM', null),
  ('D7', 'BER', 'Engin', 'BULDOZER', null),
  ('D7G', 'BER', 'Engin', 'BULDOZER', null),
  ('D7R', 'BER', 'Engin', 'BULDOZER', null),
  ('ES232AN', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('ES751AN', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('EXCA320D', 'BER', 'Engin', 'EXCAVATRICE', null),
  ('LT1300B', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT277JY', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT280JY', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT311MT', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT426MD', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SU602AT', 'BER', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VP069', 'BER', 'Camion', 'VILLE DE PARIS', null),
  ('VP077', 'BER', 'Camion', 'VILLE DE PARIS', null),
  ('AM022', 'BUE', 'Camion', 'AMPLIROLL', null),
  ('AM028', 'BUE', 'Camion', 'AMPLIROLL', null),
  ('AM032', 'BUE', 'Camion', 'AMPLIROLL', null),
  ('AM038', 'BUE', 'Camion', 'AMPLIROLL', null),
  ('AM057', 'BUE', 'Camion', 'AMPLIROLL', null),
  ('BE LO', 'BUE', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO107', 'BUE', 'Camion', 'BOM', null),
  ('BO144', 'BUE', 'Camion', 'BOM', null),
  ('BO146', 'BUE', 'Camion', 'BOM', null),
  ('PG008-01', 'BUE', 'Engin', 'PELLE CHARGEUSE', null),
  ('VP 053', 'BUE', 'Camion', 'VILLE DE PARIS', 'Doublon possible : « VP053 » (YAOUNDE)'),
  ('VP018', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('VP034', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('VP035', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('VP056', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('VP092', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('VP106', 'BUE', 'Camion', 'VILLE DE PARIS', null),
  ('ADO33AT', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('AM051', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM054', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM059', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM062', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM063', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM064', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AM_AAH', 'DLA', 'Camion', 'AMPLIROLL', null),
  ('AX003', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX004', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX005', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX006', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX007', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX008', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX009', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX010', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX011', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX012', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX_AAH', 'DLA', 'Camion', 'AMPLIROLLTRAX', null),
  ('BA015', 'DLA', 'Camion', 'BALAYEUSE', null),
  ('BA016', 'DLA', 'Camion', 'BALAYEUSE', null),
  ('BA_AAH', 'DLA', 'Camion', 'BALAYEUSE', null),
  ('BE011', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE013', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE016', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE030', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE031', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE032', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE033', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE034', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE035', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE036', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE037', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE038', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE403576', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO152', 'DLA', 'Camion', 'BOM', null),
  ('BO153', 'DLA', 'Camion', 'BOM', null),
  ('BO156', 'DLA', 'Camion', 'BOM', null),
  ('BO157', 'DLA', 'Camion', 'BOM', null),
  ('BO158', 'DLA', 'Camion', 'BOM', null),
  ('BO159', 'DLA', 'Camion', 'BOM', null),
  ('BO160', 'DLA', 'Camion', 'BOM', null),
  ('BO161', 'DLA', 'Camion', 'BOM', null),
  ('BO162', 'DLA', 'Camion', 'BOM', null),
  ('BO163', 'DLA', 'Camion', 'BOM', null),
  ('BO_AAH', 'DLA', 'Camion', 'BOM', null),
  ('BP001', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP002', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP004', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP005', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP006', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP016', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BP_AAH', 'DLA', 'Camion', 'BENNE A PALAN', null),
  ('BU02-004', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU02-009', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU02-011', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU02-012', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU02-013', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU06-001', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU06-002', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU06-003', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU_AAH', 'DLA', 'Engin', 'BULDOZER', null),
  ('BU_LO', 'DLA', 'Engin', 'BULDOZER', null),
  ('BX007', 'DLA', 'Camion', 'BOM X', null),
  ('BX010', 'DLA', 'Camion', 'BOM X', null),
  ('BX011', 'DLA', 'Camion', 'BOM X', null),
  ('BX017', 'DLA', 'Camion', 'BOM X', null),
  ('BX018', 'DLA', 'Camion', 'BOM X', null),
  ('BX020', 'DLA', 'Camion', 'BOM X', null),
  ('BX021', 'DLA', 'Camion', 'BOM X', null),
  ('BX023', 'DLA', 'Camion', 'BOM X', null),
  ('BX024', 'DLA', 'Camion', 'BOM X', null),
  ('BX025', 'DLA', 'Camion', 'BOM X', null),
  ('BX026', 'DLA', 'Camion', 'BOM X', null),
  ('BX027', 'DLA', 'Camion', 'BOM X', null),
  ('BX037', 'DLA', 'Camion', 'BOM X', null),
  ('BX_AAH', 'DLA', 'Camion', 'BOM X', null),
  ('CA006435', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CA_LO', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE017LE', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE059KO', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE101PT', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE116HY', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE182NL', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE327LU', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE337PP', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE350GY', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE475HR', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('CE476HR', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE477HR', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE479HR', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE623737', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE633PS', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE634OI', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE697LT', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE713PK', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE850GZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE868II', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE948OX', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE960HM', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH006438', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH0894929', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH093746', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH097546', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH100126', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH128785', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('CH174145', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH215425', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH228242', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH228243', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH311906', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH335386', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH373168', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH375467', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH376467', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH391349', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH399288', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH401714', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH425583', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH435986', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH4788969', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH479688', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH479HR', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH511906', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH542125', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH623737', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH770845', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH826196', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH871780', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH871880', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH877880', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('EN_ASQUINI', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EN_SECA', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX02-003', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX03-001', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX03-003', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX04-002', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX05-001', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX05-002', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX06-001', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX06-002', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX_AAH', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('EX_LO', 'DLA', 'Engin', 'EXCAVATRICE', null),
  ('GR022', 'DLA', 'Camion', 'GRUE', null),
  ('GR023', 'DLA', 'Camion', 'GRUE', null),
  ('GR024', 'DLA', 'Camion', 'GRUE', null),
  ('GR_AAH', 'DLA', 'Camion', 'GRUE', null),
  ('LT005LZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT015KA', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT024NV', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT025LK', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT026NV', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT092AP', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT116HY', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT183U', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT188LJ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT210MX', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT226KO', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT244NN', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT305AD', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT315KN', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT352LH', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT372LX', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT377NX', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT382MJ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT391LE', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT433MA', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT439GE', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT444MZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT468182', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT515MZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT516MZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT518MZ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT567LV', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT584ML', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT588MI', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT608GI', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT652AM', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT719MM', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT759JC', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT8003LW', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT806LW', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT871780', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT882MJ', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT900DU', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT903CO', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT923BS', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT941FI', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LTTR088AM', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('MG001', 'DLA', 'Camion', 'MOOVIE GRUE', null),
  ('MG_AAH', 'DLA', 'Camion', 'MOOVIE GRUE', null),
  ('NI02-001', 'DLA', 'Engin', 'NIVELLEUSE', null),
  ('PC055', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PC060', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PC061', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PC062', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PC063', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PC064', 'DLA', 'Camion', 'PORTE COFFRE', 'Doublon possible : « PC 064 » (KRIBI)'),
  ('PC_AAH', 'DLA', 'Camion', 'PORTE COFFRE', null),
  ('PG010 -001', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG05-006', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG06-001', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG07-001', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG09-001', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG09-002', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG11-001', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG11-002', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG11-003', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG11-004', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG_AAH', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG_LO', 'DLA', 'Engin', 'PELLE CHARGEUSE', null),
  ('RE005', 'DLA', 'Camion', 'REMORQUE', null),
  ('RE006', 'DLA', 'Camion', 'REMORQUE', null),
  ('RE007', 'DLA', 'Camion', 'REMORQUE', null),
  ('RE010', 'DLA', 'Camion', 'REMORQUE', null),
  ('RE012', 'DLA', 'Camion', 'REMORQUE', null),
  ('SU024AP', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SU506AX', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SU752BG', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SU758BG', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('TR003', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TR004', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TR006', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TR007', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TR009', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TR_AAH', 'DLA', 'Camion', 'TRACTEUR', null),
  ('TT01-001', 'DLA', 'Engin', 'TRACTOPELLE', null),
  ('VP051', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP057', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP094', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP095', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP096', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP097', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP098', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP100', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP101', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP102', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP108', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP109', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP111', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP112', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP115', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP116', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('VP117', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VPH5-220', 'DLA', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VP_AAH', 'DLA', 'Camion', 'VILLE DE PARIS', null),
  ('501723D', 'EBO', 'Camion', 'REMORQUE', null),
  ('822D', 'EBO', 'Engin', 'BULDOZER', null),
  ('AM073', 'EBO', 'Camion', 'AMPLIROLL', null),
  ('BE504627', 'EBO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE504628', 'EBO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE950', 'EBO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO104', 'EBO', 'Camion', 'BOM', null),
  ('BO147', 'EBO', 'Camion', 'BOM', null),
  ('BX034', 'EBO', 'Camion', 'BOM X', null),
  ('CE079BC', 'EBO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH361819', 'EBO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SEM966D', 'EBO', 'Engin', 'PELLE CHARGEUSE', null),
  ('SUD 1', 'EBO', 'Engin', 'PELLE CHARGEUSE', null),
  ('VP039', 'EBO', 'Camion', 'VILLE DE PARIS', null),
  ('VP086', 'EBO', 'Camion', 'VILLE DE PARIS', null),
  ('CHAR 1', 'EBO', 'Camion', 'REMORQUE', null),
  ('BE002', 'EDE', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE019', 'EDE', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO109', 'EDE', 'Camion', 'BOM', null),
  ('BO150', 'EDE', 'Camion', 'BOM', null),
  ('EX02-002', 'EDE', 'Engin', 'EXCAVATRICE', null),
  ('PC071', 'EDE', 'Camion', 'PORTE COFFRE', null),
  ('PG07-003', 'EDE', 'Engin', 'PELLE CHARGEUSE', null),
  ('VP037', 'EDE', 'Camion', 'VILLE DE PARIS', null),
  ('VP043', 'EDE', 'Camion', 'VILLE DE PARIS', null),
  ('VP075', 'EDE', 'Camion', 'VILLE DE PARIS', null),
  ('VP085', 'EDE', 'Camion', 'VILLE DE PARIS', null),
  ('BE004', 'GAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO080', 'GAR', 'Camion', 'BOM', null),
  ('BO108', 'GAR', 'Camion', 'BOM', null),
  ('BP012', 'GAR', 'Camion', 'BENNE A PALAN', null),
  ('BP013', 'GAR', 'Camion', 'BENNE A PALAN', null),
  ('BU02-002', 'GAR', 'Engin', 'BULDOZER', null),
  ('BU02-X13', 'GAR', 'Engin', 'BULDOZER', null),
  ('BX009', 'GAR', 'Camion', 'BOM X', null),
  ('GVP081', 'GAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('PC031', 'GAR', 'Camion', 'PORTE COFFRE', null),
  ('PC032', 'GAR', 'Camion', 'PORTE COFFRE', null),
  ('PC047', 'GAR', 'Camion', 'PORTE COFFRE', null),
  ('PC068', 'GAR', 'Camion', 'PORTE COFFRE', null),
  ('PG02-001', 'GAR', 'Engin', 'PELLE CHARGEUSE', null),
  ('VP001', 'GAR', 'Camion', 'VILLE DE PARIS', null),
  ('VP032', 'GAR', 'Camion', 'VILLE DE PARIS', null),
  ('VP033', 'GAR', 'Camion', 'VILLE DE PARIS', null),
  ('VP079', 'GAR', 'Camion', 'VILLE DE PARIS', null),
  ('VP081', 'GAR', 'Camion', 'VILLE DE PARIS', null),
  ('AMP 020', 'KRI', 'Camion', 'AMPLIROLL', null),
  ('AMP 200', 'KRI', 'Camion', 'AMPLIROLL', null),
  ('AMP 202', 'KRI', 'Camion', 'AMPLIROLL', null),
  ('BE01', 'KRI', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE02', 'KRI', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE03', 'KRI', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE04', 'KRI', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE05', 'KRI', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO084', 'KRI', 'Camion', 'BOM', null),
  ('BO170', 'KRI', 'Camion', 'BOM', null),
  ('BX015', 'KRI', 'Camion', 'BOM X', null),
  ('GR020', 'KRI', 'Camion', 'GRUE', null),
  ('GR021', 'KRI', 'Camion', 'GRUE', null),
  ('MB013', 'KRI', 'Camion', 'MINI BOM', null),
  ('MG 002', 'KRI', 'Camion', 'MOOVIE GRUE', 'Doublon possible : « MG002 » (BAFOUSSAM)'),
  ('PC 064', 'KRI', 'Camion', 'PORTE COFFRE', 'Doublon possible : « PC064 » (DOUALA)'),
  ('VP 071', 'KRI', 'Camion', 'VILLE DE PARIS', 'Doublon possible : « VP071 » (YAOUNDE)'),
  ('VP041', 'KRI', 'Camion', 'VILLE DE PARIS', null),
  ('VP105', 'KRI', 'Camion', 'VILLE DE PARIS', null),
  ('966', 'KUM', 'Engin', 'PELLE CHARGEUSE', null),
  ('AM045', 'KUM', 'Camion', 'AMPLIROLL', null),
  ('AM058', 'KUM', 'Camion', 'AMPLIROLL', null),
  ('BO099', 'KUM', 'Camion', 'BOM', null),
  ('BX035', 'KUM', 'Camion', 'BOM X', null),
  ('CH730266', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CH96831', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('ES577AL', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('L55B5', 'KUM', 'Engin', 'PELLE CHARGEUSE', null),
  ('LT092GM', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT093', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT295', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('NM134AA', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('NW134AA', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('PG05-002', 'KUM', 'Engin', 'PELLE CHARGEUSE', null),
  ('SEM 655 D', 'KUM', 'Engin', 'PELLE CHARGEUSE', 'Doublon possible : « SEM655D » (KUMBA)'),
  ('SEM655D', 'KUM', 'Engin', 'PELLE CHARGEUSE', 'Doublon possible : « SEM 655 D » (KUMBA)'),
  ('SU345AO', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('SW 068', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « SW068 » (KUMBA)'),
  ('SW068', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', 'Doublon possible : « SW 068 » (KUMBA)'),
  ('SW306BV', 'KUM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VP048', 'KUM', 'Camion', 'VILLE DE PARIS', null),
  ('VP107', 'KUM', 'Camion', 'VILLE DE PARIS', null),
  ('AM004', 'LIM', 'Camion', 'AMPLIROLL', null),
  ('BE LCC', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE LOC', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO072', 'LIM', 'Camion', 'BOM', null),
  ('BO094', 'LIM', 'Camion', 'BOM', null),
  ('BO145', 'LIM', 'Camion', 'BOM', null),
  ('BU02-003', 'LIM', 'Engin', 'BULDOZER', null),
  ('BX008', 'LIM', 'Camion', 'BOM X', null),
  ('BX022', 'LIM', 'Camion', 'BOM X', null),
  ('CE 827 NG', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('CE 943 HC', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT 162 EQ', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT 304 TR', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT 447 GT', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('LT 686 LQ', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('NW 898 GN', 'LIM', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('PC027', 'LIM', 'Camion', 'PORTE COFFRE', null),
  ('PC033', 'LIM', 'Camion', 'PORTE COFFRE', null),
  ('PC045', 'LIM', 'Camion', 'PORTE COFFRE', null),
  ('PG 08-001', 'LIM', 'Engin', 'PELLE CHARGEUSE', null),
  ('VP025', 'LIM', 'Camion', 'VILLE DE PARIS', null),
  ('VP044', 'LIM', 'Camion', 'VILLE DE PARIS', null),
  ('VP072', 'LIM', 'Camion', 'VILLE DE PARIS', null),
  ('VP103', 'LIM', 'Camion', 'VILLE DE PARIS', null),
  ('000056', 'MAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('550262', 'MAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE023', 'MAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BP014', 'MAR', 'Camion', 'BENNE A PALAN', null),
  ('BP015', 'MAR', 'Camion', 'BENNE A PALAN', null),
  ('BU02-X12', 'MAR', 'Engin', 'BULDOZER', null),
  ('BX012', 'MAR', 'Camion', 'BOM X', null),
  ('PC058', 'MAR', 'Camion', 'PORTE COFFRE', null),
  ('PC069', 'MAR', 'Camion', 'PORTE COFFRE', null),
  ('PG03-002', 'MAR', 'Engin', 'PELLE CHARGEUSE', null),
  ('SU551AX', 'MAR', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('VP076', 'MAR', 'Camion', 'VILLE DE PARIS', null),
  ('VP082', 'MAR', 'Camion', 'VILLE DE PARIS', null),
  ('BO106', 'MEY', 'Camion', 'BOM', null),
  ('AM052', 'NGA', 'Camion', 'AMPLIROLL', null),
  ('AM071', 'NGA', 'Camion', 'AMPLIROLL', null),
  ('BO073', 'NGA', 'Camion', 'BOM', null),
  ('BO169', 'NGA', 'Camion', 'BOM', null),
  ('VP083', 'NGA', 'Camion', 'VILLE DE PARIS', null),
  ('VP084', 'NGA', 'Camion', 'VILLE DE PARIS', null),
  ('BO033', 'SAN', 'Camion', 'BOM', null),
  ('BO171', 'SAN', 'Camion', 'BOM', null),
  ('VP104', 'SAN', 'Camion', 'VILLE DE PARIS', null),
  ('VP104S', 'SAN', 'Camion', 'VILLE DE PARIS', null),
  ('AM056', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM060', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM061', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM065', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM066', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM068', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM069', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AM072', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AUTRE AGENCE', 'YAO', 'Camion', 'AMPLIROLL', null),
  ('AX001', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX002', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX013', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX014', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX015', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX016', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX017', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('AX018', 'YAO', 'Camion', 'AMPLIROLLTRAX', null),
  ('BA013', 'YAO', 'Camion', 'BALAYEUSE', null),
  ('BA014', 'YAO', 'Camion', 'BALAYEUSE', null),
  ('BA017', 'YAO', 'Camion', 'BALAYEUSE', null),
  ('BA018', 'YAO', 'Camion', 'BALAYEUSE', null),
  ('BE008', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE012', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE017', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE020', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE021', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE022', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE024', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE025', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE026', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE027', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE028', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BE029', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BENNE LOCATION', 'YAO', 'Camion', 'BENNE ENTREPRENEUR', null),
  ('BO141', 'YAO', 'Camion', 'BOM', null),
  ('BO148', 'YAO', 'Camion', 'BOM', null),
  ('BO149', 'YAO', 'Camion', 'BOM', null),
  ('BO151', 'YAO', 'Camion', 'BOM', null),
  ('BO154', 'YAO', 'Camion', 'BOM', null),
  ('BO155', 'YAO', 'Camion', 'BOM', null),
  ('BO164', 'YAO', 'Camion', 'BOM', null),
  ('BO166', 'YAO', 'Camion', 'BOM', null),
  ('BO167', 'YAO', 'Camion', 'BOM', null),
  ('BP007', 'YAO', 'Camion', 'BENNE A PALAN', null),
  ('BP008', 'YAO', 'Camion', 'BENNE A PALAN', null),
  ('BP009', 'YAO', 'Camion', 'BENNE A PALAN', null),
  ('BP010', 'YAO', 'Camion', 'BENNE A PALAN', null),
  ('BP011', 'YAO', 'Camion', 'BENNE A PALAN', null),
  ('BU02-014', 'YAO', 'Engin', 'BULDOZER', null),
  ('BU02-015', 'YAO', 'Engin', 'BULDOZER', null),
  ('BU02-016', 'YAO', 'Engin', 'BULDOZER', null),
  ('BU02-X11', 'YAO', 'Engin', 'BULDOZER', null),
  ('BU05-001', 'YAO', 'Engin', 'BULDOZER', null),
  ('BX001', 'YAO', 'Camion', 'BOM X', null),
  ('BX002', 'YAO', 'Camion', 'BOM X', null),
  ('BX003', 'YAO', 'Camion', 'BOM X', null),
  ('BX004', 'YAO', 'Camion', 'BOM X', null),
  ('BX005', 'YAO', 'Camion', 'BOM X', null),
  ('BX006', 'YAO', 'Camion', 'BOM X', null),
  ('BX013', 'YAO', 'Camion', 'BOM X', null),
  ('BX019', 'YAO', 'Camion', 'BOM X', null),
  ('BX028', 'YAO', 'Camion', 'BOM X', null),
  ('BX029', 'YAO', 'Camion', 'BOM X', null),
  ('BX030', 'YAO', 'Camion', 'BOM X', null),
  ('BX031', 'YAO', 'Camion', 'BOM X', null),
  ('BX033', 'YAO', 'Camion', 'BOM X', null),
  ('EX01-003', 'YAO', 'Engin', 'EXCAVATRICE', null),
  ('EX03-002', 'YAO', 'Engin', 'EXCAVATRICE', null),
  ('EX04-001', 'YAO', 'Engin', 'EXCAVATRICE', null),
  ('EX04-003', 'YAO', 'Engin', 'EXCAVATRICE', null),
  ('EX07-002', 'YAO', 'Engin', 'EXCAVATRICE', null),
  ('GR018', 'YAO', 'Camion', 'GRUE', null),
  ('GR025', 'YAO', 'Camion', 'GRUE', null),
  ('GR026', 'YAO', 'Camion', 'GRUE', null),
  ('GR027', 'YAO', 'Camion', 'GRUE', null),
  ('GR028', 'YAO', 'Camion', 'GRUE', null),
  ('GROUPE ELECTROGENE CTD', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('MG003', 'YAO', 'Camion', 'MOOVIE GRUE', null),
  ('MG004', 'YAO', 'Camion', 'MOOVIE GRUE', null),
  ('PC051', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC052', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC054', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC057', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC065', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC066', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PC067', 'YAO', 'Camion', 'PORTE COFFRE', null),
  ('PELLE LOCATION', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG05-001', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG05-003', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG06-002', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG07-002', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG08-002', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG08-003', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG09-003', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('PG09-004', 'YAO', 'Engin', 'PELLE CHARGEUSE', null),
  ('RE001', 'YAO', 'Camion', 'REMORQUE', null),
  ('RE002', 'YAO', 'Camion', 'REMORQUE', null),
  ('RE003', 'YAO', 'Camion', 'REMORQUE', null),
  ('RE004', 'YAO', 'Camion', 'REMORQUE', null),
  ('RE008', 'YAO', 'Camion', 'REMORQUE', null),
  ('RE009', 'YAO', 'Camion', 'REMORQUE', null),
  ('TR001', 'YAO', 'Camion', 'TRACTEUR', null),
  ('TR002', 'YAO', 'Camion', 'TRACTEUR', null),
  ('TR005', 'YAO', 'Camion', 'TRACTEUR', null),
  ('TR008', 'YAO', 'Camion', 'TRACTEUR', null),
  ('TR010', 'YAO', 'Camion', 'TRACTEUR', null),
  ('TT01-002', 'YAO', 'Engin', 'TRACTOPELLE', null),
  ('VP052', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP053', 'YAO', 'Camion', 'VILLE DE PARIS', 'Doublon possible : « VP 053 » (BUEA)'),
  ('VP060', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP061', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP062', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP063', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP064', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP065', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP066', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP067', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP068', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP070', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP071', 'YAO', 'Camion', 'VILLE DE PARIS', 'Doublon possible : « VP 071 » (KRIBI)'),
  ('VP073', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP074', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP090', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP091', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP110', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP113', 'YAO', 'Camion', 'VILLE DE PARIS', null),
  ('VP114', 'YAO', 'Camion', 'VILLE DE PARIS', null)
on conflict (code) do update set agence_code = excluded.agence_code, famille = excluded.famille,
  type_vehicule = excluded.type_vehicule, remarque = excluded.remarque;

-- Seuils du suivi des opérations (préfixe exploit_) : conservés pour référence, sans effet sur les règles MAD.
insert into parametres(cle, valeur, libelle) values
  ('exploit_taux_realisation_min', 90, '[Suivi des opérations] Taux de réalisation (%) en dessous duquel l''agence est en alerte'),
  ('exploit_taux_realisation_critique', 60, '[Suivi des opérations] Taux de réalisation (%) critique'),
  ('exploit_taux_realisation_suspect', 150, '[Suivi des opérations] Taux (%) au-dessus duquel l''objectif est probablement sous-évalué'),
  ('exploit_traitement_vs_collecte_tolerance', 5, '[Suivi des opérations] Écart toléré (%) entre tonnage traité Hysacam et tonnage collecté'),
  ('exploit_tdi_min', 60, '[Suivi des opérations] Disponibilité camions (%) minimale'),
  ('exploit_tdi_critique', 40, '[Suivi des opérations] Disponibilité camions (%) critique'),
  ('exploit_tdi_engin_min', 50, '[Suivi des opérations] Disponibilité engins (%) minimale'),
  ('exploit_pesee_auto_min', 90, '[Suivi des opérations] Part de pesée automatique (%) minimale quand le pont est disponible'),
  ('exploit_pesee_auto_critique', 50, '[Suivi des opérations] Part de pesée automatique (%) critique'),
  ('exploit_ecart_carburant_pct', 2, '[Suivi des opérations] Écart de stock carburant (%) toléré'),
  ('exploit_ecart_carburant_critique_fcfa', 1000000, '[Suivi des opérations] Écart carburant (FCFA) classé critique'),
  ('exploit_prix_gasoil', 828, '[Suivi des opérations] Prix du litre de gasoil (FCFA)'),
  ('exploit_prix_essence', 840, '[Suivi des opérations] Prix du litre d''essence (FCFA)'),
  ('exploit_autonomie_min_jours', 3, '[Suivi des opérations] Autonomie carburant (jours) sous laquelle il y a risque de rupture'),
  ('exploit_maj_retard_jours', 2, '[Suivi des opérations] Retard de saisie carburant (jours) toléré'),
  ('exploit_part_nombres_ronds_max', 60, '[Suivi des opérations] Part (%) maximale de pleins en multiples de 50 L'),
  ('exploit_rotations_facteur', 2, '[Suivi des opérations] Alerte si rotations/sortie > facteur x médiane du même type de véhicule'),
  ('exploit_litre_par_tonne_facteur', 2, '[Suivi des opérations] Alerte si L/t > facteur x médiane du même type de véhicule'),
  ('exploit_part_location_max', 20, '[Suivi des opérations] Part (%) maximale du tonnage réalisé en location'),
  ('exploit_assiduite_min', 80, '[Suivi des opérations] Taux d''assiduité (%) minimal'),
  ('exploit_assiduite_critique', 75, '[Suivi des opérations] Taux d''assiduité (%) critique'),
  ('exploit_abs_non_justifiee_max', 2, '[Suivi des opérations] Absences non justifiées (% de l''effectif) tolérées'),
  ('exploit_chute_assiduite_points', 15, '[Suivi des opérations] Chute journalière d''assiduité (points) sous la moyenne de l''agence'),
  ('exploit_jours_valeur_identique', 4, '[Suivi des opérations] Nombre de jours avec une valeur strictement identique = données recopiées')
on conflict (cle) do nothing;
